# Generated by Django 5.2.5 on 2025-08-30 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='link',
            new_name='certificate_url',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='name',
            new_name='provider',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issuer',
        ),
        migrations.AddField(
            model_name='certification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certification',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
